[WIP] Nessie Catalog Support
nk1506/airbyte pull request #1
Opened 2023-11-10 09:48 UTC by nk1506

2023-11-17 06:24 UTC, ajantha-bhat requested changes
There are some blunders in the integration tests and quality of the PR can be improved.

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/IcebergCatalogConfigFactory.java
> -      default -> throw new RuntimeException("Unexpected catalog config: " + catalogTypeStr);
we still need the default case for other catalogs like Glue, DynamoDB etc

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/NessieCatalogConfig.java
> +  private final String token;
Can you check how to configure the `warehouse` location?

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/NessieCatalogConfig.java
> +    Preconditions.checkArgument(null != catalogConfig.get(NESSIE_CATALOG_REFERENCE_KEY), "%s is required", NESSIE_CATALOG_REFERENCE_KEY);
If not specified we can use default main branch. It is not mandatory to configure this.

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/NessieCatalogConfig.java
> +    Preconditions.checkArgument(null != catalogConfig.get(NESSIE_CATALOG_AUTHENTICATION_TYPE_KEY), "%s is required", NESSIE_CATALOG_AUTHENTICATION_TYPE_KEY);
if not configured we can use No authentication.

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/NessieCatalogConfig.java
> +  private final String token;
`FileIO` also need to be configured along with warehouse.

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/NessieCatalogConfig.java
> +    configMap.put("spark.driver.extraJavaOptions", "-Dpackaging.type=jar -Djava.io.tmpdir=/tmp");
So these Nessie spark SQL extension jars need to be placed in class path?

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/NessieCatalogConfig.java
> +    if (isNotBlank(this.token)) {
Authentication type is not honoured.

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/NessieCatalogConfig.java
> +  private final String token;
ok. I saw `this.storageConfig.getWarehouseUri()` below in `genCatalog`. But we still need to expose `io-impl ` for FileIO.

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/resources/spec.json
> +                "examples": ["http://localhost:19120"],
It will have `/api/v1` like that

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/resources/spec.json
> +              "nessie_auth_type": {
auth type and auth token are two different parameter

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/test-integration/java/io/airbyte/integrations/destination/iceberg/nessie/BaseIcebergNessieCatalogS3IntegrationTest.java
> +    LOGGER.info("==> Started REST Server with Minio - Docker Compose...");
```suggestion
    LOGGER.info("==> Started Nessie Server with Minio - Docker Compose...");
```

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/test-integration/java/io/airbyte/integrations/destination/iceberg/nessie/BaseIcebergNessieCatalogS3IntegrationTest.java
> +  private static RESTServerWithMinioCompose composeContainer;
Wrong class? Should be Nessie?

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/test-integration/java/io/airbyte/integrations/destination/iceberg/nessie/BaseIcebergNessieCatalogS3IntegrationTest.java
> +    IcebergIntegrationTestUtil.stopAndCloseContainer(composeContainer, "REST Server with Minio - Docker Compose");
Please check this class, I think Integration test is running with Rest server. Not the Nessie.

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/test-integration/resources/nessie-catalog-compose.yml
> +      - CATALOG_WAREHOUSE=s3://warehouse/rest
```suggestion
      - CATALOG_WAREHOUSE=s3://warehouse/nessie
```

2023-11-17 06:24 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/test-integration/java/io/airbyte/integrations/destination/iceberg/container/NessieServerWithMinioCompose.java
> +    return "http://localhost:" + getServicePort(NESSIE_SERVICE_NAME, NESSIE_SERVER_PORT);
This will not work. 

Nessie Uri need a suffix like /api/v1
https://iceberg.apache.org/docs/latest/nessie/#nessie-catalog

2023-11-21 07:26 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/IcebergCatalogConfigFactory.java
> -      default -> throw new RuntimeException("Unexpected catalog config: " + catalogTypeStr);
why this is not handled?

2023-11-21 07:33 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/NessieCatalogConfig.java
> +    if (isNotBlank(this.token)) {
I mean if we have auth type none and user configures token. We should throw exception. Check if the underlying code handles it by adding a test case.

2023-11-21 07:35 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/main/resources/spec.json
> +                "examples": ["V1", "V2"],
I think the values are 1 and 2. Not v1 and V2

2023-11-21 07:37 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/test-integration/java/io/airbyte/integrations/destination/iceberg/container/NessieServerWithMinioCompose.java
> +    return "http://localhost:" + getServicePort(NESSIE_SERVICE_NAME, NESSIE_SERVER_PORT) + "/api/"+NESSIE_API_VERSION;
please handle formatting. Space needed before NESSIE_API_VERSION

2023-11-21 07:40 UTC, ajantha-bhat commented on airbyte-integrations/connectors/destination-iceberg/src/test-integration/resources/nessie-catalog-compose.yml
> +      - AWS_ACCESS_KEY_ID=admin
I don't think we need these env variables. Please test it without them once.

2023-11-22 09:28 UTC, nk1506 commented on airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/IcebergCatalogConfigFactory.java
> -      default -> throw new RuntimeException("Unexpected catalog config: " + catalogTypeStr);
Switch case is accepting enum as [catalogType](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/CatalogType.java) . All the possible cases have been already covered. IMO, Compiler will never reach to Default case.

2023-11-22 09:30 UTC, nk1506 commented on airbyte-integrations/connectors/destination-iceberg/src/main/java/io/airbyte/integrations/destination/iceberg/config/catalog/NessieCatalogConfig.java
> +    configMap.put("spark.driver.extraJavaOptions", "-Dpackaging.type=jar -Djava.io.tmpdir=/tmp");
I have added as gradle [dependency](https://github.com/nk1506/airbyte/pull/1/files#diff-9051cf60a5d2dd7ebea1c9def6be1bd477581dca18fec14270d5e59a38a547f5R27).

2023-11-24 06:13 UTC, nk1506 commented
Raised the same [PR](https://github.com/airbytehq/airbyte/pull/32720) with airbyte. So closing this.

2023-11-24 06:13 UTC, closed without merging